routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\TicketController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\WilayahController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ComplainController;
use App\Http\Controllers\Admin\HelperController;
use App\Http\Controllers\Admin\BranchController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\SendMailController;
use App\Http\Controllers\Admin\ReportController;

Route::get('/', [LoginController::class, 'showLoginForm']);
Route::redirect('/home', '/admin');

Auth::routes();
Route::group(['prefix' => 'admin', 'as' => 'admin.','middleware' => ['auth']], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    //Ticket
    Route::resource('/ticket', TicketController::class);
    Route::get('/ticket-ajax', [TicketController::class, 'ticketAjax'])->name('ticket-ajax');
    Route::get('/ticket/option/{id}', [TicketController::class, 'ticketOption'])->name('ticket.option');
    Route::get('/ticket/action/{id}', [TicketController::class, 'action'])->name('ticket.action');
    Route::get('/ticket/issabel/{id}/{agent}/{call}/{campaign}/{callid}/{remote}', [TicketController::class, 'tiketPhone'])->name('ticket.issabel');
    Route::get('ticket/print/{id}', [TicketController::class, 'print'])->name('ticket.print');
    Route::get('ticket/xls/{id}', [TicketController::class, 'xls'])->name('ticket.xls');

    //Report
    Route::get('/report-komplain', [ReportController::class, 'reportKomplain'])->name('report-komplain');
    Route::get('/report-komplain-data', [ReportController::class, 'reportKomplainData'])->name('report-komplain-data');
    Route::get('/report-komplain-export', [ReportController::class, 'reportKomplainExport'])->name('report-komplain-export');
    Route::get('/report-wilayah', [ReportController::class, 'reportWilayah'])->name('report-wilayah');
    Route::get('/report-wilayah-data', [ReportController::class, 'reportWilayahData'])->name('report-wilayah-data');
    Route::get('/report-wilayah-export', [ReportController::class, 'reportWilayahExport'])->name('report-wilayah-export');
    Route::get('/report-kategori', [ReportController::class, 'reportKategori'])->name('report-kategori');
    Route::get('/report-kategori-data', [ReportController::class, 'reportKategoriData'])->name('report-kategori-data');
    Route::get('/report-kategori-export', [ReportController::class, 'reportKategoriExport'])->name('report-kategori-export');

    Route::view('/maintenance', 'maintenance.index')->name('maintenance');

    //Email
    Route::get('/kirim-email', [SendMailController::class, 'send']);

    //Helpers
    Route::get('/cust-details', [HelperController::class, 'custDetail'])->name('cust-details');
    Route::get('/select-cust', [HelperController::class, 'selectCust'])->name('select-cust');

    //Settings
    Route::resource('/cust', CustomerController::class);
    Route::get('/cust-ajax', [CustomerController::class, 'custAjax'])->name('cust-ajax');
    Route::resource('/branch', BranchController::class);
    Route::resource('/region', RegionController::class);
    Route::resource('/role', RoleController::class);
    Route::get('/role/edit-menu-access', [RoleController::class, 'roleMenu'])->name('role.edit-menu-access');
    Route::post('/role/store-menu-access', [RoleController::class, 'postRoleMenu'])->name('role.store-menu-access');
    Route::get('/complain/edit-alternative/{id}', [ComplainController::class, 'editAlterNative'])->name('complain.edit-alternative');
	Route::resource('/complain', ComplainController::class);
    Route::resource('/menu', MenuController::class);
    Route::resource('/user', UserController::class);
    Route::resource('/setting', SettingController::class);

});

// Route::get('/home', [HomeController::class, 'index'])->name('home');

resources/views/pages/cust/create.blade.php
<div id="display-errors"></div>
<input type="hidden" name="id" id="id">
<div class="form-group">
    <label>Customer Number <b class="label-required">*</b></label>
    <input type="text" id="no_pelanggan" name="no_pelanggan" class="form-control add" value="{{ old('no_pelanggan') }}">
    <span class="text-danger error-text no_pelanggan_err">
        <strong id="no_pelanggan-error"></strong>
    </span>
</div>
<div class="row">
    <div class="col">
        <div class="form-group">
            <label>Customer Name <b class="label-required">*</b></label>
            <input type="text" id="realname" name="realname" class="form-control add" value="{{ old('realname') }}">
            <span class="text-danger error-text realname_err">
                <strong id="realname-error"></strong>
            </span>
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            <label>Outlet Name <b class="label-required">*</b></label>
            <input type="text" id="outlet_name" name="outlet_name" class="form-control add" value="{{ old('outlet_name') }}">
            <span class="text-danger error-text name_err">
                <strong id="outlet_name-error"></strong>
            </span>
        </div>
    </div>
</div>
<div class="form-group">
    <label>Phone Number <b class="label-required">*</b></label>
    <input type="text" id="phone_no" name="phone_no" onkeyup="numericFilter(this);" class="form-control add" value="{{ old('phone_no') }}">
    <span class="text-danger error-text phone_no_err">
        <strong id="phone_no-error"></strong>
    </span>
</div>
<div class="row">
    <div class="col">
        <div class="form-group">
            <label>SPV Name <b class="label-required">*</b></label>
            <input type="text" id="spv_sales" name="spv_sales" class="form-control add" value="{{ old('spv_sales') }}">
            <span class="text-danger error-text spv_sales_err">
                <strong id="spv_sales-error"></strong>
            </span>
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            <label>Sales Name <b class="label-required">*</b></label>
            <input type="text" id="salesname" name="salesname" class="form-control add" value="{{ old('salesname') }}">
            <span class="text-danger error-text salesname_err">
                <strong id="salesname-error"></strong>
            </span>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="form-group">
            <label>Branch <b class="label-required">*</b></label>
            <select class="select2 form-control" style="width: 100%;" name="branch_id" id="branch_id">
                <option value=""> Pilih </option>
                @foreach ($branch as $id => $item)
                    <option value="{{ $item->id }}">{{ $item->code }}-{{ $item->name }}</option>
                @endforeach
            </select>
            <span class="text-danger error-text branch_id_err">
                <strong id="branch_id-error"></strong>
            </span>
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            <label>Type Outlet <b class="label-required">*</b></label>
            <select class="select2 form-control" style="width: 100%;" name="type_outlet_id" id="type_outlet_id">
                <option value=""> Pilih </option>
                @foreach ($type_outlet as $id => $item)
                    <option value="{{ $id }}">{{ $item }}</option>
                @endforeach
            </select>
            <span class="text-danger error-text type_outlet_id_err">
                <strong id="type_outlet_id-error"></strong>
            </span>
        </div>
    </div>
</div>
<div class="form-group">
    <label>Address <b class="label-required">*</b></label>
    <textarea class="form-control add" id="alamat" name="alamat">{{ old('alamat') }}</textarea>
    <span class="text-danger error-text alamat_err">
        <strong id="alamat-error"></strong>
    </span>
</div>

resources/views/pages/cust/edit.blade.php
<div id="display-errors"></div>
<input type="hidden" name="id" id="id" value="{{ $customer->id }}">
<div class="form-group">
    <label>Customer Number <b class="label-required">*</b></label>
    <input type="text" id="no_pelanggan" name="no_pelanggan" class="form-control add" value="{{ old('no_pelanggan') }}">
    <span class="text-danger error-text no_pelanggan_err">
        <strong id="no_pelanggan-error"></strong>
    </span>
</div>
<div class="row">
    <div class="col">
        <div class="form-group">
            <label>Customer Name <b class="label-required">*</b></label>
            <input type="text" id="realname" name="realname" class="form-control add" value="{{ old('realname', $customer->realname) }}">
            <span class="text-danger error-text realname_err">
                <strong id="realname-error"></strong>
            </span>
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            <label>Outlet Name <b class="label-required">*</b></label>
            <input type="text" id="outlet_name" name="outlet_name" class="form-control add" value="{{ old('outlet_name', $customer->outlet_name) }}">
            <span class="text-danger error-text name_err">
                <strong id="outlet_name-error"></strong>
            </span>
        </div>
    </div>
</div>
<div class="form-group">
    <label>Phone Number <b class="label-required">*</b></label>
    <input type="text" id="phone_no" name="phone_no" onkeyup="numericFilter(this);" class="form-control add" value="{{ old('phone_no', $customer->phone_no) }}">
    <span class="text-danger error-text phone_no_err">
        <strong id="phone_no-error"></strong>
    </span>
</div>
<div class="row">
    <div class="col">
        <div class="form-group">
            <label>SPV Name <b class="label-required">*</b></label>
            <input type="text" id="spv_sales" name="spv_sales" class="form-control add" value="{{ old('spv_sales', $customer->spv_sales) }}">
            <span class="text-danger error-text spv_sales_err">
                <strong id="spv_sales-error"></strong>
            </span>
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            <label>Sales Name <b class="label-required">*</b></label>
            <input type="text" id="salesname" name="salesname" class="form-control add" value="{{ old('salesname', $customer->salesname) }}">
            <span class="text-danger error-text salesname_err">
                <strong id="salesname-error"></strong>
            </span>
        </div>
    </div>
</div>
<div class="form-group">
    <label>Type Outlet <b class="label-required">*</b></label>
    <select class="select2 form-control" style="width: 100%;" name="type_outlet_id" id="type_outlet_id">
        <option value=""> Pilih </option>
        @foreach ($type_outlet as $id => $item)
            <option value="{{ $id }}" @if($customer->type_outlet_id == $id) selected @endif >{{ $item }}</option>
        @endforeach
    </select>
    <span class="text-danger error-text type_outlet_id_err">
        <strong id="type_outlet_id-error"></strong>
    </span>
</div>

<div class="form-group">
    <label>Address <b class="label-required">*</b></label>
    <textarea class="form-control add" id="alamat" name="alamat">{{ old('alamat', $customer->alamat) }}</textarea>
    <span class="text-danger error-text alamat_err">
        <strong id="alamat-error"></strong>
    </span>
</div>

resources/views/pages/cust/index.blade.php
@section('title', 'Customer')
@extends('layouts.master')
@push('custom-css')
<link rel="stylesheet" href="{{ asset('assets/modules/selectric/public/selectric.css') }}">
@endpush
@section('header', 'Customer')
@section('content')
<div class="section-body">
    <div class="row mt-4">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="section-header-button">
                        <button class="btn btn-primary add-new" id="add-index">
                            <i class="far fa-plus-square"></i> Add New
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="ajax-table" class="table table-bordered table-striped table-hover datatable datatable-Role">
                            <thead>
                                <tr>
                                    <th>Nomor Pelanggan</th>
                                    <th>Name</th>
                                    <th>Outlet Name</th>
                                    <th>Phone Number</th>
                                    <th>Author</th>
                                    <th>&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($data as $item => $raw)
                                <tr>
                                    <td>{{ $raw->no_pelanggan }}</td>
                                    <td>{{ $raw->realname }}</td>
                                    <td>{{ $raw->outlet_name }}</td>
                                    <td>{{ $raw->phone_no }}</td>
                                    <td>{{ \Penolong::getName($raw->updated_by)->name ?? \Penolong::getName($raw->created_by)->name }}</td>
                                    <td>
                                        <a class="badge badge-info show-index" id="show_{{ $item }}" data-id="{{ $raw->id }}" href="#">
                                            <i class="fa fa-eye"></i> Show
                                        </a> &nbsp;
                                        <a class="badge badge-warning edit-index" data-name="update" id="edit_{{ $item }}" data-id="{{ $raw->id }}" href="#">
                                            <i class="fa fa-edit"></i> Edit
                                        </a> &nbsp;
                                        <a class="badge del-index badge-danger" data-name="{{ $raw->outlet_name }}" data-id="{{ $raw->id }}" href="#">
                                            <form action="{{ route('admin.cust.destroy', $raw->id) }}" id="delete_{{ $raw->id }}" method="POST">
                                                @csrf
                                                @method('delete')
                                            </form>
                                            <i class="fa fa-trash"></i> Delete
                                        </a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-right">
                            {!! $data->links() !!}
                        </div>
                        {{-- {{ $data->links() }} --}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@include('pages.cust.modal')
@endsection
@push('custom-js')
<script src="{{ asset('assets/js/pages/cust.js') }}"></script>
@endpush

resources/views/pages/cust/modal.blade.php
@section('modal')
{{-- create-modal --}}
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" id="createModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-white">New Customer</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {{-- action="{{ route('admin.cust.store') }}" method="POST"  --}}
            <form id="modal-store" enctype="multipart/form-data">
                @csrf
                <div class="modal-body">
                    {{-- ?? --}}
                </div>
                <div class="modal-footer bg-whitesmoke br">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" id="btn-save" class="btn btn-primary"><i class="fa fa-save"></i> Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

{{-- edit modal --}}
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" id="updateModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-warning">
                <h5 class="text-white modal-title">Edit Customer</h5>
                <button type="button" class="text-white close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="modal-update" enctype="multipart/form-data">
                @csrf
                <div class="modal-body">
                    {{-- ?? --}}
                </div>
                <div class="modal-footer bg-whitesmoke br">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" id="btn-update" class="btn btn-primary"><i class="fa fa-save"></i> Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

{{-- show modal --}}
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" id="showModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-info">
                <h5 class="text-white modal-title">Show Customer</h5>
                <button type="button" class="text-white close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{-- ?? --}}
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/pages/cust/show.blade.php
<div id="display-errors"></div>
<input type="hidden" name="id" id="id" value="{{ $customer->id }}">
<div class="row">
    <div class="col">
        <div class="form-group">
            <label>Customer Name <b class="label-required">*</b></label>
            <input type="text" id="realname" name="realname" class="form-control add" value="{{ old('realname', $customer->realname) }}" readonly>
            <span class="text-danger error-text realname_err">
                <strong id="realname-error"></strong>
            </span>
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            <label>Outlet Name <b class="label-required">*</b></label>
            <input type="text" id="outlet_name" name="outlet_name" class="form-control add" value="{{ old('outlet_name', $customer->outlet_name) }}" readonly>
            <span class="text-danger error-text name_err">
                <strong id="outlet_name-error"></strong>
            </span>
        </div>
    </div>
</div>
<div class="form-group">
    <label>Phone Number <b class="label-required">*</b></label>
    <input type="text" id="phone_no" name="phone_no" onkeyup="numericFilter(this);" class="form-control add" value="{{ old('phone_no', $customer->phone_no) }}" readonly>
    <span class="text-danger error-text phone_no_err">
        <strong id="phone_no-error"></strong>
    </span>
</div>
<div class="row">
    <div class="col">
        <div class="form-group">
            <label>SPV Name <b class="label-required">*</b></label>
            <input type="text" id="spv_sales" name="spv_sales" class="form-control add" value="{{ old('spv_sales', $customer->spv_sales) }}" readonly>
            <span class="text-danger error-text spv_sales_err">
                <strong id="spv_sales-error"></strong>
            </span>
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            <label>Sales Name <b class="label-required">*</b></label>
            <input type="text" id="salesname" name="salesname" class="form-control add" value="{{ old('salesname', $customer->salesname) }}" readonly>
            <span class="text-danger error-text salesname_err">
                <strong id="salesname-error"></strong>
            </span>
        </div>
    </div>
</div>
<div class="form-group">
    <label>Type Outlet <b class="label-required">*</b></label>
    <select class="select2 form-control" style="width: 100%;" name="type_outlet_id" id="type_outlet_id" readonly>
        <option value=""> Pilih </option>
        @foreach ($type_outlet as $id => $item)
            <option value="{{ $id }}" @if($customer->type_outlet_id == $id) selected @endif >{{ $item }}</option>
        @endforeach
    </select>
    <span class="text-danger error-text type_outlet_id_err">
        <strong id="type_outlet_id-error"></strong>
    </span>
</div>

<div class="form-group">
    <label>Address <b class="label-required">*</b></label>
    <textarea class="form-control add" id="alamat" name="alamat" readonly>{{ old('alamat', $customer->alamat) }}</textarea>
    <span class="text-danger error-text alamat_err">
        <strong id="alamat-error"></strong>
    </span>
</div>