routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\TicketController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\WilayahController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ComplainController;
use App\Http\Controllers\Admin\HelperController;
use App\Http\Controllers\Admin\BranchController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\SendMailController;
use App\Http\Controllers\Admin\ReportController;

Route::get('/', [LoginController::class, 'showLoginForm']);
Route::redirect('/home', '/admin');

Auth::routes();
Route::group(['prefix' => 'admin', 'as' => 'admin.','middleware' => ['auth']], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    //Ticket
    Route::resource('/ticket', TicketController::class);
    Route::get('/ticket-ajax', [TicketController::class, 'ticketAjax'])->name('ticket-ajax');
    Route::get('/ticket/option/{id}', [TicketController::class, 'ticketOption'])->name('ticket.option');
    Route::get('/ticket/action/{id}', [TicketController::class, 'action'])->name('ticket.action');
    Route::get('/ticket/issabel/{id}/{agent}/{call}/{campaign}/{callid}/{remote}', [TicketController::class, 'tiketPhone'])->name('ticket.issabel');
    Route::get('ticket/print/{id}', [TicketController::class, 'print'])->name('ticket.print');
    Route::get('ticket/xls/{id}', [TicketController::class, 'xls'])->name('ticket.xls');

    //Report
    Route::get('/report-komplain', [ReportController::class, 'reportKomplain'])->name('report-komplain');
    Route::get('/report-komplain-data', [ReportController::class, 'reportKomplainData'])->name('report-komplain-data');
    Route::get('/report-komplain-export', [ReportController::class, 'reportKomplainExport'])->name('report-komplain-export');
    Route::get('/report-wilayah', [ReportController::class, 'reportWilayah'])->name('report-wilayah');
    Route::get('/report-wilayah-data', [ReportController::class, 'reportWilayahData'])->name('report-wilayah-data');
    Route::get('/report-wilayah-export', [ReportController::class, 'reportWilayahExport'])->name('report-wilayah-export');
    Route::get('/report-kategori', [ReportController::class, 'reportKategori'])->name('report-kategori');
    Route::get('/report-kategori-data', [ReportController::class, 'reportKategoriData'])->name('report-kategori-data');
    Route::get('/report-kategori-export', [ReportController::class, 'reportKategoriExport'])->name('report-kategori-export');

    Route::view('/maintenance', 'maintenance.index')->name('maintenance');

    //Email
    Route::get('/kirim-email', [SendMailController::class, 'send']);

    //Helpers
    Route::get('/cust-details', [HelperController::class, 'custDetail'])->name('cust-details');
    Route::get('/select-cust', [HelperController::class, 'selectCust'])->name('select-cust');

    //Settings
    Route::resource('/cust', CustomerController::class);
    Route::get('/cust-ajax', [CustomerController::class, 'custAjax'])->name('cust-ajax');
    Route::resource('/branch', BranchController::class);
    Route::resource('/region', RegionController::class);
    Route::resource('/role', RoleController::class);
    Route::get('/role/edit-menu-access', [RoleController::class, 'roleMenu'])->name('role.edit-menu-access');
    Route::post('/role/store-menu-access', [RoleController::class, 'postRoleMenu'])->name('role.store-menu-access');
    Route::get('/complain/edit-alternative/{id}', [ComplainController::class, 'editAlterNative'])->name('complain.edit-alternative');
	Route::resource('/complain', ComplainController::class);
    Route::resource('/menu', MenuController::class);
    Route::resource('/user', UserController::class);
    Route::resource('/setting', SettingController::class);

});

// Route::get('/home', [HomeController::class, 'index'])->name('home');

app/Http/Controllers/Admin/ComplainController.php
<?php

namespace App\Http\Controllers\Admin;

use Carbon\Carbon;
use App\Http\Controllers\Controller;
use App\Models\VariableComplain;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class ComplainController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $data = Role::paginate(2);
        $data = VariableComplain::orderBy('name')->get();

        return view('pages.complain.index', compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        DB::beginTransaction();
        try {
            // $this->_validation($request);

            $store = VariableComplain::create($request->all());
            DB::commit();

            return redirect()->route('admin.complain.index');
        } catch (\Throwable $th) {
            DB::rollback();
            throw $th;
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\VariableComplain  $variableComplain
     * @return \Illuminate\Http\Response
     */
    public function show(VariableComplain $variableComplain)
    {
        return view('pages.complain.show', compact('variableComplain'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\VariableComplain  $variableComplain
     * @return \Illuminate\Http\Response
     */
    public function edit(VariableComplain $id)
    {
        $edit = VariableComplain::findOrFail($id);

        return view('pages.complain.edit', compact('edit'));
    }

    public function editAlterNative($id)
    {
        $edit = VariableComplain::findOrFail($id);

        return view('pages.complain.edit', compact('edit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\VariableComplain  $variableComplain
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, VariableComplain $variableComplain)
    {
        DB::beginTransaction();
        try {
            // $this->_validation($request);

            $update = VariableComplain::findOrFail($request->id);
            $update->name = $request->name;
            $update->update();

            DB::commit();

        } catch (\Throwable $th) {
            DB::rollback();
            throw $th;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\VariableComplain  $variableComplain
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $del = VariableComplain::findOrFail($id);
        $del->deleted_at = Carbon::now();
        $del->update();

        return back();
    }
}

resources/views/pages/complain/edit.blade.php
<div id="display-errors"></div>
<input type="hidden" name="id" id="id" value="{{ $edit->id }}">
<input type="hidden" name="action_post" id="action_post">
<div class="form-group">
    <label>Variable Name <b class="label-required">*</b></label>
    <input type="text" id="name" name="name" class="form-control update" value="{{ $edit->name }}">
    <span class="text-danger error-text name_err">
        <strong id="name-error"></strong>
    </span>
</div>

resources/views/pages/complain/index.blade.php
@section('title', 'Variable Complain')
@extends('layouts.master')
@push('custom-css')
{{-- <link rel="stylesheet" href="{{ asset('assets/modules/selectric/public/selectric.css') }}"> --}}
@endpush
@section('header', 'Variable Complain')
@section('content')
<div class="section-body">
    <div class="row mt-4">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="section-header-button">
                        <button class="btn btn-primary add-index" id="add-index" data-name="add"><i class="far fa-plus-square"></i> Add New</a></button>
                    </div>
                    <hr>
                    @if(session('message'))
                        <div class="alert alert-success alert-has-icon">
                            <div class="alert-icon"><i class="far fa-lightbulb"></i></div>
                            <div class="alert-body">
                                <div class="alert-title">Success</div>
                                {{ session('message') }}
                            </div>
                        </div>
                    @endif
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="index-table" class="table table-bordered table-striped table-hover datatable datatable-Role">
                            <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Name</th>
                                    <th>Created By</th>
                                    <th>&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($data as $key => $item)
                                    <tr data-entry-id="{{ $item->id }}">
                                        <td>
                                            {{ $key+1 }}
                                        </td>
                                        <td>
                                            {{ $item->name ?? '' }}
                                        </td>
                                        <td>
                                            {{ \Penolong::getName($item->created_by)->name ?? '' }}
                                        </td>
                                        <td>
                                            <a class="badge badge-info show-index" data-id="{{ $item->id }}" id="show_{{ $item->id }}" href="#">
                                                <i class="fa fa-eye"></i> Show
                                            </a>
                                            <a class="badge badge-warning edit-index" data-id="{{ $item->id }}" id="edit_{{ $item->id }}" href="#">
                                                <i class="fa fa-edit"></i> Edit
                                            </a>
                                            <a class="badge del-index badge-danger" data-name="{{ $item->name }}" data-id="{{ $item->id }}" href="#">
                                                <form action="{{ route('admin.complain.destroy', $item->id) }}" id="delete_{{ $item->id }}" method="POST">
                                                    @csrf
                                                    @method('delete')
                                                </form>
                                                <i class="fa fa-trash"></i> Delete
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{-- {{ $data->links() }} --}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@include('pages.complain.modal')
@endsection
@push('custom-js')
    <script src="{{ asset('assets/js/pages/complain.js') }}"></script>
@endpush

resources/views/pages/complain/modal.blade.php
@section('modal')
{{-- create-modal --}}
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" id="createModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-white">New Variable</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {{-- action="{{ route('admin.cust.store') }}" method="POST"  --}}
            <form id="modal-store" enctype="multipart/form-data">
                @csrf
                <div class="modal-body">
                    <div id="display-errors"></div>
                    <div class="form-group">
                        <label>Variable Name <b class="label-required">*</b></label>
                        <input type="text" id="name" name="name" class="form-control add" value="{{ old('name') }}">
                        <span class="text-danger error-text name_err">
                            <strong id="name-error"></strong>
                        </span>
                    </div>
                </div>
                <div class="modal-footer bg-whitesmoke br">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" id="btn-save" class="btn btn-primary"><i class="fa fa-save"></i> Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

{{-- edit modal --}}
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" id="updateModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-warning">
                <h5 class="text-white modal-title">Edit Variable</h5>
                <button type="button" class="text-white close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="modal-update" enctype="multipart/form-data">
                @csrf
                <div class="modal-body">
                    {{-- ?? --}}
                </div>
                <div class="modal-footer bg-whitesmoke br">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" id="btn-update" class="btn btn-primary"><i class="fa fa-save"></i> Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

{{-- show modal --}}
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" id="showModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-info">
                <h5 class="text-white modal-title">Show Variable</h5>
                <button type="button" class="text-white close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{-- ?? --}}
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/pages/complain/show.blade.php
<div id="display-errors"></div>
<input type="hidden" name="id" id="id" value="{{ $variableComplain->id }}">
<div class="form-group">
    <label>Variable Name <b class="label-required">*</b></label>
    <input type="text" id="name" name="name" class="form-control update" value="{{ $variableComplain->name }}" disabled>
    <span class="text-danger error-text name_err"></span>
</div>