routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\TicketController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\WilayahController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ComplainController;
use App\Http\Controllers\Admin\HelperController;
use App\Http\Controllers\Admin\BranchController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\SendMailController;
use App\Http\Controllers\Admin\ReportController;

Route::get('/', [LoginController::class, 'showLoginForm']);
Route::redirect('/home', '/admin');

Auth::routes();
Route::group(['prefix' => 'admin', 'as' => 'admin.','middleware' => ['auth']], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    //Ticket
    Route::resource('/ticket', TicketController::class);
    Route::get('/ticket-ajax', [TicketController::class, 'ticketAjax'])->name('ticket-ajax');
    Route::get('/ticket/option/{id}', [TicketController::class, 'ticketOption'])->name('ticket.option');
    Route::get('/ticket/action/{id}', [TicketController::class, 'action'])->name('ticket.action');
    Route::get('/ticket/issabel/{id}/{agent}/{call}/{campaign}/{callid}/{remote}', [TicketController::class, 'tiketPhone'])->name('ticket.issabel');
    Route::get('ticket/print/{id}', [TicketController::class, 'print'])->name('ticket.print');
    Route::get('ticket/xls/{id}', [TicketController::class, 'xls'])->name('ticket.xls');

    //Report
    Route::get('/report-komplain', [ReportController::class, 'reportKomplain'])->name('report-komplain');
    Route::get('/report-komplain-data', [ReportController::class, 'reportKomplainData'])->name('report-komplain-data');
    Route::get('/report-komplain-export', [ReportController::class, 'reportKomplainExport'])->name('report-komplain-export');
    Route::get('/report-wilayah', [ReportController::class, 'reportWilayah'])->name('report-wilayah');
    Route::get('/report-wilayah-data', [ReportController::class, 'reportWilayahData'])->name('report-wilayah-data');
    Route::get('/report-wilayah-export', [ReportController::class, 'reportWilayahExport'])->name('report-wilayah-export');
    Route::get('/report-kategori', [ReportController::class, 'reportKategori'])->name('report-kategori');
    Route::get('/report-kategori-data', [ReportController::class, 'reportKategoriData'])->name('report-kategori-data');
    Route::get('/report-kategori-export', [ReportController::class, 'reportKategoriExport'])->name('report-kategori-export');

    Route::view('/maintenance', 'maintenance.index')->name('maintenance');

    //Email
    Route::get('/kirim-email', [SendMailController::class, 'send']);

    //Helpers
    Route::get('/cust-details', [HelperController::class, 'custDetail'])->name('cust-details');
    Route::get('/select-cust', [HelperController::class, 'selectCust'])->name('select-cust');

    //Settings
    Route::resource('/cust', CustomerController::class);
    Route::get('/cust-ajax', [CustomerController::class, 'custAjax'])->name('cust-ajax');
    Route::resource('/branch', BranchController::class);
    Route::resource('/region', RegionController::class);
    Route::resource('/role', RoleController::class);
    Route::get('/role/edit-menu-access', [RoleController::class, 'roleMenu'])->name('role.edit-menu-access');
    Route::post('/role/store-menu-access', [RoleController::class, 'postRoleMenu'])->name('role.store-menu-access');
    Route::get('/complain/edit-alternative/{id}', [ComplainController::class, 'editAlterNative'])->name('complain.edit-alternative');
	Route::resource('/complain', ComplainController::class);
    Route::resource('/menu', MenuController::class);
    Route::resource('/user', UserController::class);
    Route::resource('/setting', SettingController::class);

});

// Route::get('/home', [HomeController::class, 'index'])->name('home');

resources/views/layouts/header.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
            <li>
                <a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a>
            </li>
            <li>
                <a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a>
            </li>
        </ul>
    </form>
    <ul class="navbar-nav ml-auto">
        <li class="dropdown dropdown-list-toggle">
            <a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg @if(count(\Penolong::cekNotif()) > 0) beep @endif">
                <span class="badge badge-danger ml-2">{{ count(\Penolong::cekNotif()) }}</span> {{-- notif --}}
                <i class="far fa-bell"></i>
            </a>
            <div class="dropdown-menu dropdown-list dropdown-menu-right">
                <div class="dropdown-header">
                    Notifications
                </div>
                <div class="dropdown-list-content dropdown-list-icons">
                    @foreach (\Penolong::cekNotif() as $key => $item )
                        <a href="{{ route('admin.ticket.action', $item->id) }}" class="dropdown-item dropdown-item-unread">
                            <div class="dropdown-item-icon
                                @if($item->main_status_id == 300) bg-danger
                                @elseif ($item->main_status_id == 102) bg-warning
                                @elseif ($item->main_status_id == 200) bg-success @endif
                            text-white">
                                <i class="fas fa-ticket-alt"></i>
                            </div>
                            <div class="dropdown-item-desc">
                                No. Reff: {{ $item->no_ref }}<br>Pelanggan : @if($item->customer_id == "") {{ $item->realname }} @else  {{ \Penolong::getCust($item->customer_id)->realname }} @endif
                                <div class="time text-primary">{{ \Penolong::time_elapsed_string($item->created_at) }}</div>
                            </div>
                        </a>
                    @endforeach
                </div>
                <div class="dropdown-footer text-center">
                    Notifications
                </div>
            </div>
        </li>
        <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
            <img alt="image" src="{{ asset('avatars/luffy-avatar.png') }}" class="rounded-circle mr-1">
            <div class="d-sm-none d-lg-inline-block">Hi, {{ \Auth::user()->name }}</div></a>
            <div class="dropdown-menu dropdown-menu-right">
                {{-- <a href="features-profile.html" class="dropdown-item has-icon">
                    <i class="far fa-user"></i> Profile
                </a> --}}
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item has-icon text-danger" onclick="event.preventDefault();document.getElementById('formLogOut').submit();">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>
                <form id="formLogOut" action="{{ route('logout') }}" method="POST">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>{{ config('app.name') }} - @yield('title')</title>

    {{-- General CSS Files --}}
    {{-- <link rel="stylesheet" href="{{ asset('assets/bootstrap/bootstrap.min.css') }}"> --}}
    <link rel="stylesheet" href="{{ asset('assets/bootstrap-4.6.0-dist/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ asset('assets/fontawesome/all.css') }}">
    <link href="{{ asset('assets/css/custom.css') }}" rel="stylesheet">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('logo/logo.png') }}">

    {{-- CSS Modules --}}
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/modules/DataTables/datatables.min.css')}}"/>
    <link href="{{asset('assets/modules/select2/dist/css/select2.min.css')}}" rel="stylesheet" />
    <link href="{{ asset('assets/modules/jquery-ui-1.12.1/jquery-ui.css')}}" rel="stylesheet" />
    {{-- <link href="{{ asset('assets/modules/daterangepicker/daterangepicker.css')}}" rel="stylesheet" /> --}}
    <link rel="stylesheet" href="{{ asset('assets/modules/sweetalert2/dist/sweetalert2.min.css') }}" />
    {{-- <link rel="stylesheet" type="text/css" href="{{ asset('assets/modules/bootstrap-timepicker/css/bootstrap-timepicker.min.css') }}" /> --}}
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/modules/jquery-datetimepicker/jquery.datetimepicker.css') }}" />
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    {{-- Template CSS --}}
    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/components.css') }}">
    <link href="{{ asset('assets/css/global.css') }}" rel="stylesheet">
    @stack('custom-css')
</head>
<body>
    <div id="app">
        <div class="main-wrapper">
            <div class="navbar-bg"></div>

            @include('layouts.header')

            @include('layouts.sidebar')
            {{-- Main Content --}}
            <div class="main-content">
                <section class="section">
                    <div class="section-header">
                        <h1>@yield('header')</h1>
                    </div>
                    @yield('content')
                </section>
                @yield('modal')
            </div>
            <footer class="main-footer">
                <div class="footer-left">
                    Copyright &copy; {{ date("Y") }} <div class="bullet"></div> Design By <a href="https://gitlab.com/zaychsual" target="_blank">Fastrata</a>
                </div>
            </footer>
        </div>
    </div>
    @stack('before-script')
    {{--  General JS Scripts --}}
    <script src="{{ asset('assets/javascript/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ asset('assets/javascript/popper.min.js') }}"></script>
    {{-- <script src="{{ asset('assets/javascript/bootstrap.min.js') }}"></script> --}}
    <script src="{{ asset('assets/bootstrap-4.6.0-dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/javascript/jquery.nicescroll.min.js') }}"></script>
    <script src="{{ asset('assets/javascript/moment.min.js') }}"></script>
    <script src="{{ asset('assets/js/stisla.js') }}"></script>

    {{-- JS Modules --}}
    <script src="{{asset('assets/modules/sweetalert2/dist/sweetalert2.all.min.js')}}"></script>
    <script src="{{ asset('assets/modules/sweetalert/dist/sweetalert.min.js') }}"></script>
    <script type="text/javascript" charset="utf8" src="{{ asset('assets/modules/DataTables/datatables.min.js') }}"></script>
    {{-- <script src="{{ asset('assets/modules/bootstrap-timepicker/js/bootstrap-timepicker.min.js') }}"></script> --}}
    <script src="{{ asset('assets/modules/select2/dist/js/select2.full.min.js')}}"></script>
    <script src="{{ asset('assets/modules/jquery-ui-1.12.1/jquery-ui.js') }}"></script>
    {{-- <script src="{{ asset('assets/modules/daterangepicker/daterangepicker.js') }}"></script> --}}
    <script src="{{ asset('assets/modules/php-date-formatter/js/php-date-formatter.min.js') }}"></script>
    <script src="{{ asset('assets/modules/jquery-mousewheel/jquery.mousewheel.js') }}"></script>
    {{-- <script src="{{ asset('assets/modules/jquery-datetimepicker/jquery-datetimepicker.js') }}"></script> --}}
    <script src="{{ asset('assets/modules/jquery-datetimepicker/jquery.datetimepicker.js') }}"></script>
    {{-- Template JS File --}}
    <script src="{{ asset('assets/js/scripts.js') }}"></script>
    <script src="{{ asset('assets/js/custom.js') }}"></script>
    <script src="{{ asset('assets/js/global.js') }}"></script>
    {{-- Page Specific Custom Javascript --}}
    @stack('custom-js')
</body>
</html>

resources/views/layouts/sidebar.blade.php
<div class="main-sidebar">
	<aside id="sidebar-wrapper">
		<div class="sidebar-brand">
			<a href="{{ route('admin.dashboard') }}" class="navbar-brand">
                <img src="{{ asset('logo/logo.png') }}" class="sidebar-logo" width="100" class="shadow-light rounded-circle" alt="{{ env('APP_NAME') }}">
            </a><br>
            <span>{{ config('app.name') }}</span>
            {{-- <a href="index.html">Stisla</a> --}}
		</div>
		<div class="sidebar-brand sidebar-brand-sm">
            <a href="{{ route('admin.dashboard') }}">
                <img src="{{ asset('logo/logo.png') }}" class="sidebar-logo" width="35" class="shadow-light rounded-circle">
            </a>
		</div>
        <ul class="sidebar-menu">
            @foreach (\Penolong::mainMenu() as $row => $mm)
                @php
                    $subMenu = \Penolong::cekSubMenu($mm->id);
                    $menuAktif = \Penolong::cekMenuAktif(Request::segment(2));
                @endphp
                <li @if(Request::segment(2) == $mm->menu_aktif || $menuAktif->master_menu == $mm->id) class="active" @endif>
                    <a href="@if(isset($mm->url)) {{ route('admin.'.$mm->url.'') }} @else # @endif"
                        @if($subMenu) class="nav-link has-dropdown" @endif>
                        <i class="{{ $mm->icon }}"></i>
                        <span>{{ $mm->name }}</span>
                    </a>
                    @if($subMenu)
                        <ul class="dropdown-menu">
                    @endif
                    @foreach (\Penolong::subMenu() as $sm)
                        @if ($sm->master_menu == $mm->id)
                        <li @if(Request::segment(2) == $sm->menu_aktif) class="active" @endif>
                            <a class="nav-link" href="{{ route('admin.'.$sm->url.'') }}">
                                {{ $sm->name }}
                            </a>
                        </li>
                        @endif
                    @endforeach
                    @if($subMenu)
                        </ul>
                    @endif
                </li>
            @endforeach
        </ul>
	</aside>
</div>